defaultSemverRangePrefix: ""

packageExtensions:
    "@prisma/client@*":
        dependencies:
            .prisma: 'link:See "resolution" field of package.json'

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
      spec: "@yarnpkg/plugin-workspace-tools"
    - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
      spec: "@yarnpkg/plugin-typescript"
    - path: .yarn/plugins/@yarnpkg/plugin-production-install.cjs
      spec: "https://gitlab.com/Larry1123/yarn-contrib/-/raw/master/packages/plugin-production-install/bundles/@yarnpkg/plugin-production-install.js"

yarnPath: .yarn/releases/yarn-3.6.0.cjs
