services:
  back:
    image: vanchenkin/merestorage:back-latest
    build:
      dockerfile: ./docker/back.Dockerfile
      context: .
    # env_file:
    #   - .env
    ports:
      - 3000:3000
  postgres:
    image: postgres
    restart: always
    environment:
      # POSTGRES_DB: ${POSTGRES_DB}
      # POSTGRES_USER: ${POSTGRES_USER}
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "123"
      POSTGRES_USER: "123"
      POSTGRES_PASSWORD: "123"
    ports:
      - 5434:5432
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
  front:
    image: vanchenkin/merestorage:front-latest
    build:
      context: .
      dockerfile: ./docker/front.Dockerfile
    restart: always
    ports:
      - 8080:8080

volumes:
  docker-nest-postgres:
