services:
  back:
    image: vanchenkin/merestorage:back-latest
    build:
      dockerfile: ./docker/back.Dockerfile
      context: .
    ports:
      - 3000:3000
  front:
    image: vanchenkin/merestorage:front-latest
    build:
      context: .
      dockerfile: ./docker/front.Dockerfile
    restart: always
    ports:
      - 8080:8080

volumes:
  docker-nest-postgres:
